// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	TgId          string                 `protobuf:"bytes,5,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	Bio           string                 `protobuf:"bytes,6,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetTgId() string {
	if x != nil {
		return x.TgId
	}
	return ""
}

func (x *CreateUserRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *CreateUserRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type IsSubscribedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FollowingId   string                 `protobuf:"bytes,2,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsSubscribedRequest) Reset() {
	*x = IsSubscribedRequest{}
	mi := &file_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsSubscribedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsSubscribedRequest) ProtoMessage() {}

func (x *IsSubscribedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsSubscribedRequest.ProtoReflect.Descriptor instead.
func (*IsSubscribedRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *IsSubscribedRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *IsSubscribedRequest) GetFollowingId() string {
	if x != nil {
		return x.FollowingId
	}
	return ""
}

type IsSubscribedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSubscribed  bool                   `protobuf:"varint,1,opt,name=is_subscribed,json=isSubscribed,proto3" json:"is_subscribed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsSubscribedResponse) Reset() {
	*x = IsSubscribedResponse{}
	mi := &file_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsSubscribedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsSubscribedResponse) ProtoMessage() {}

func (x *IsSubscribedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsSubscribedResponse.ProtoReflect.Descriptor instead.
func (*IsSubscribedResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *IsSubscribedResponse) GetIsSubscribed() bool {
	if x != nil {
		return x.IsSubscribed
	}
	return false
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          []*UserResponse        `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserResponse) Reset() {
	*x = ListUserResponse{}
	mi := &file_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserResponse) ProtoMessage() {}

func (x *ListUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserResponse.ProtoReflect.Descriptor instead.
func (*ListUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *ListUserResponse) GetUser() []*UserResponse {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ListUserResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type IsAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgID          string                 `protobuf:"bytes,1,opt,name=tgID,proto3" json:"tgID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAdminRequest) Reset() {
	*x = IsAdminRequest{}
	mi := &file_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAdminRequest) ProtoMessage() {}

func (x *IsAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAdminRequest.ProtoReflect.Descriptor instead.
func (*IsAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *IsAdminRequest) GetTgID() string {
	if x != nil {
		return x.TgID
	}
	return ""
}

type IsAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAdmin       bool                   `protobuf:"varint,1,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAdminResponse) Reset() {
	*x = IsAdminResponse{}
	mi := &file_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAdminResponse) ProtoMessage() {}

func (x *IsAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAdminResponse.ProtoReflect.Descriptor instead.
func (*IsAdminResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *IsAdminResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type AddAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgID          string                 `protobuf:"bytes,1,opt,name=tgID,proto3" json:"tgID,omitempty"`
	AddedBy       string                 `protobuf:"bytes,2,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAdminRequest) Reset() {
	*x = AddAdminRequest{}
	mi := &file_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAdminRequest) ProtoMessage() {}

func (x *AddAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAdminRequest.ProtoReflect.Descriptor instead.
func (*AddAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *AddAdminRequest) GetTgID() string {
	if x != nil {
		return x.TgID
	}
	return ""
}

func (x *AddAdminRequest) GetAddedBy() string {
	if x != nil {
		return x.AddedBy
	}
	return ""
}

type AddAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAdminResponse) Reset() {
	*x = AddAdminResponse{}
	mi := &file_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAdminResponse) ProtoMessage() {}

func (x *AddAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAdminResponse.ProtoReflect.Descriptor instead.
func (*AddAdminResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *AddAdminResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AddAdminResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgID          string                 `protobuf:"bytes,1,opt,name=tgID,proto3" json:"tgID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAdminRequest) Reset() {
	*x = RemoveAdminRequest{}
	mi := &file_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAdminRequest) ProtoMessage() {}

func (x *RemoveAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAdminRequest.ProtoReflect.Descriptor instead.
func (*RemoveAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveAdminRequest) GetTgID() string {
	if x != nil {
		return x.TgID
	}
	return ""
}

type RemoveAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAdminResponse) Reset() {
	*x = RemoveAdminResponse{}
	mi := &file_proto_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAdminResponse) ProtoMessage() {}

func (x *RemoveAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAdminResponse.ProtoReflect.Descriptor instead.
func (*RemoveAdminResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveAdminResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RemoveAdminResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetUserByTgIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          string                 `protobuf:"bytes,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByTgIDRequest) Reset() {
	*x = GetUserByTgIDRequest{}
	mi := &file_proto_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByTgIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTgIDRequest) ProtoMessage() {}

func (x *GetUserByTgIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTgIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByTgIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserByTgIDRequest) GetTgId() string {
	if x != nil {
		return x.TgId
	}
	return ""
}

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          string                 `protobuf:"bytes,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_proto_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterUserRequest) GetTgId() string {
	if x != nil {
		return x.TgId
	}
	return ""
}

func (x *RegisterUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterUserRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *RegisterUserRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *RegisterUserRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	TgId          string                 `protobuf:"bytes,4,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_proto_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UpdateUserRequest) GetTgId() string {
	if x != nil {
		return x.TgId
	}
	return ""
}

func (x *UpdateUserRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateUserRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type UserResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Age            int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	TgId           string                 `protobuf:"bytes,5,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	Username       string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Bio            string                 `protobuf:"bytes,8,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl      string                 `protobuf:"bytes,9,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	PostsCount     int32                  `protobuf:"varint,10,opt,name=posts_count,json=postsCount,proto3" json:"posts_count,omitempty"`
	FollowersCount int32                  `protobuf:"varint,11,opt,name=followers_count,json=followersCount,proto3" json:"followers_count,omitempty"`
	FollowingCount int32                  `protobuf:"varint,12,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_proto_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{15}
}

func (x *UserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResponse) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserResponse) GetTgId() string {
	if x != nil {
		return x.TgId
	}
	return ""
}

func (x *UserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserResponse) GetPostsCount() int32 {
	if x != nil {
		return x.PostsCount
	}
	return 0
}

func (x *UserResponse) GetFollowersCount() int32 {
	if x != nil {
		return x.FollowersCount
	}
	return 0
}

func (x *UserResponse) GetFollowingCount() int32 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          string                 `protobuf:"bytes,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,3,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_proto_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{16}
}

func (x *CreatePostRequest) GetTgId() string {
	if x != nil {
		return x.TgId
	}
	return ""
}

func (x *CreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePostRequest) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_proto_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{17}
}

func (x *GetPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type GetUserPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          string                 `protobuf:"bytes,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPostsRequest) Reset() {
	*x = GetUserPostsRequest{}
	mi := &file_proto_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPostsRequest) ProtoMessage() {}

func (x *GetUserPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPostsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPostsRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserPostsRequest) GetTgId() string {
	if x != nil {
		return x.TgId
	}
	return ""
}

func (x *GetUserPostsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserPostsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Для проверки прав
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_proto_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{19}
}

func (x *DeletePostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *DeletePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PostResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PostId         string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	AuthorTgId     string                 `protobuf:"bytes,2,opt,name=author_tg_id,json=authorTgId,proto3" json:"author_tg_id,omitempty"`
	AuthorName     string                 `protobuf:"bytes,3,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorUsername string                 `protobuf:"bytes,4,opt,name=author_username,json=authorUsername,proto3" json:"author_username,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	MediaUrl       string                 `protobuf:"bytes,6,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CommentsCount  int32                  `protobuf:"varint,9,opt,name=comments_count,json=commentsCount,proto3" json:"comments_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	mi := &file_proto_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{20}
}

func (x *PostResponse) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PostResponse) GetAuthorTgId() string {
	if x != nil {
		return x.AuthorTgId
	}
	return ""
}

func (x *PostResponse) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *PostResponse) GetAuthorUsername() string {
	if x != nil {
		return x.AuthorUsername
	}
	return ""
}

func (x *PostResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostResponse) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *PostResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PostResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *PostResponse) GetCommentsCount() int32 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

type PostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostResponse        `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostsResponse) Reset() {
	*x = PostsResponse{}
	mi := &file_proto_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostsResponse) ProtoMessage() {}

func (x *PostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostsResponse.ProtoReflect.Descriptor instead.
func (*PostsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{21}
}

func (x *PostsResponse) GetPosts() []*PostResponse {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *PostsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type PostWithCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *PostResponse          `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	Comments      []*CommentResponse     `protobuf:"bytes,2,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostWithCommentsResponse) Reset() {
	*x = PostWithCommentsResponse{}
	mi := &file_proto_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostWithCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostWithCommentsResponse) ProtoMessage() {}

func (x *PostWithCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostWithCommentsResponse.ProtoReflect.Descriptor instead.
func (*PostWithCommentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{22}
}

func (x *PostWithCommentsResponse) GetPost() *PostResponse {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *PostWithCommentsResponse) GetComments() []*CommentResponse {
	if x != nil {
		return x.Comments
	}
	return nil
}

type AddCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	TgId          string                 `protobuf:"bytes,2,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentRequest) Reset() {
	*x = AddCommentRequest{}
	mi := &file_proto_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentRequest) ProtoMessage() {}

func (x *AddCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentRequest.ProtoReflect.Descriptor instead.
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{23}
}

func (x *AddCommentRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *AddCommentRequest) GetTgId() string {
	if x != nil {
		return x.TgId
	}
	return ""
}

func (x *AddCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsRequest) Reset() {
	*x = GetCommentsRequest{}
	mi := &file_proto_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsRequest) ProtoMessage() {}

func (x *GetCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{24}
}

func (x *GetCommentsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *GetCommentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCommentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CommentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommentId      string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	PostId         string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	AuthorTgId     string                 `protobuf:"bytes,3,opt,name=author_tg_id,json=authorTgId,proto3" json:"author_tg_id,omitempty"`
	AuthorName     string                 `protobuf:"bytes,4,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`             // Имя автора
	AuthorUsername string                 `protobuf:"bytes,5,opt,name=author_username,json=authorUsername,proto3" json:"author_username,omitempty"` // @username автора
	Content        string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommentResponse) Reset() {
	*x = CommentResponse{}
	mi := &file_proto_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentResponse) ProtoMessage() {}

func (x *CommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentResponse.ProtoReflect.Descriptor instead.
func (*CommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{25}
}

func (x *CommentResponse) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *CommentResponse) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *CommentResponse) GetAuthorTgId() string {
	if x != nil {
		return x.AuthorTgId
	}
	return ""
}

func (x *CommentResponse) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *CommentResponse) GetAuthorUsername() string {
	if x != nil {
		return x.AuthorUsername
	}
	return ""
}

func (x *CommentResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentResponse     `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentsResponse) Reset() {
	*x = CommentsResponse{}
	mi := &file_proto_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsResponse) ProtoMessage() {}

func (x *CommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsResponse.ProtoReflect.Descriptor instead.
func (*CommentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{26}
}

func (x *CommentsResponse) GetComments() []*CommentResponse {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *CommentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`    // Кто подписывается
	FollowingId   string                 `protobuf:"bytes,2,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"` // На кого подписывается
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{27}
}

func (x *SubscribeRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *SubscribeRequest) GetFollowingId() string {
	if x != nil {
		return x.FollowingId
	}
	return ""
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FollowingId   string                 `protobuf:"bytes,2,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_proto_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{28}
}

func (x *UnsubscribeRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *UnsubscribeRequest) GetFollowingId() string {
	if x != nil {
		return x.FollowingId
	}
	return ""
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_proto_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{29}
}

func (x *SubscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubscribeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedRequest) Reset() {
	*x = GetFeedRequest{}
	mi := &file_proto_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedRequest) ProtoMessage() {}

func (x *GetFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedRequest.ProtoReflect.Descriptor instead.
func (*GetFeedRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{30}
}

func (x *GetFeedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFeedRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFeedRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_user_proto protoreflect.FileDescriptor

const file_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x10proto/user.proto\x12\auser.v1\"\xb1\x01\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x13\n" +
	"\x05tg_id\x18\x05 \x01(\tR\x04tgId\x12\x10\n" +
	"\x03bio\x18\x06 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tR\tavatarUrl\"Y\n" +
	"\x13IsSubscribedRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x02 \x01(\tR\vfollowingId\";\n" +
	"\x14IsSubscribedResponse\x12#\n" +
	"\ris_subscribed\x18\x01 \x01(\bR\fisSubscribed\"C\n" +
	"\x10ListUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"^\n" +
	"\x10ListUserResponse\x12)\n" +
	"\x04user\x18\x01 \x03(\v2\x15.user.v1.UserResponseR\x04user\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"$\n" +
	"\x0eIsAdminRequest\x12\x12\n" +
	"\x04tgID\x18\x01 \x01(\tR\x04tgID\",\n" +
	"\x0fIsAdminResponse\x12\x19\n" +
	"\bis_admin\x18\x01 \x01(\bR\aisAdmin\"@\n" +
	"\x0fAddAdminRequest\x12\x12\n" +
	"\x04tgID\x18\x01 \x01(\tR\x04tgID\x12\x19\n" +
	"\badded_by\x18\x02 \x01(\tR\aaddedBy\"<\n" +
	"\x10AddAdminResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"(\n" +
	"\x12RemoveAdminRequest\x12\x12\n" +
	"\x04tgID\x18\x01 \x01(\tR\x04tgID\"?\n" +
	"\x13RemoveAdminResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x0eGetUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"+\n" +
	"\x14GetUserByTgIDRequest\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\tR\x04tgId\"\x9d\x01\n" +
	"\x13RegisterUserRequest\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\tR\x04tgId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\"\x98\x01\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x13\n" +
	"\x05tg_id\x18\x04 \x01(\tR\x04tgId\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\"\xd7\x02\n" +
	"\fUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x13\n" +
	"\x05tg_id\x18\x05 \x01(\tR\x04tgId\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x10\n" +
	"\x03bio\x18\b \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\t \x01(\tR\tavatarUrl\x12\x1f\n" +
	"\vposts_count\x18\n" +
	" \x01(\x05R\n" +
	"postsCount\x12'\n" +
	"\x0ffollowers_count\x18\v \x01(\x05R\x0efollowersCount\x12'\n" +
	"\x0ffollowing_count\x18\f \x01(\x05R\x0efollowingCount\"_\n" +
	"\x11CreatePostRequest\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\tR\x04tgId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tmedia_url\x18\x03 \x01(\tR\bmediaUrl\")\n" +
	"\x0eGetPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"[\n" +
	"\x13GetUserPostsRequest\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\tR\x04tgId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"E\n" +
	"\x11DeletePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xaf\x02\n" +
	"\fPostResponse\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12 \n" +
	"\fauthor_tg_id\x18\x02 \x01(\tR\n" +
	"authorTgId\x12\x1f\n" +
	"\vauthor_name\x18\x03 \x01(\tR\n" +
	"authorName\x12'\n" +
	"\x0fauthor_username\x18\x04 \x01(\tR\x0eauthorUsername\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1b\n" +
	"\tmedia_url\x18\x06 \x01(\tR\bmediaUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12%\n" +
	"\x0ecomments_count\x18\t \x01(\x05R\rcommentsCount\"]\n" +
	"\rPostsResponse\x12+\n" +
	"\x05posts\x18\x01 \x03(\v2\x15.user.v1.PostResponseR\x05posts\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"{\n" +
	"\x18PostWithCommentsResponse\x12)\n" +
	"\x04post\x18\x01 \x01(\v2\x15.user.v1.PostResponseR\x04post\x124\n" +
	"\bcomments\x18\x02 \x03(\v2\x18.user.v1.CommentResponseR\bcomments\"[\n" +
	"\x11AddCommentRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x13\n" +
	"\x05tg_id\x18\x02 \x01(\tR\x04tgId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"^\n" +
	"\x12GetCommentsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xee\x01\n" +
	"\x0fCommentResponse\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\x12 \n" +
	"\fauthor_tg_id\x18\x03 \x01(\tR\n" +
	"authorTgId\x12\x1f\n" +
	"\vauthor_name\x18\x04 \x01(\tR\n" +
	"authorName\x12'\n" +
	"\x0fauthor_username\x18\x05 \x01(\tR\x0eauthorUsername\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"i\n" +
	"\x10CommentsResponse\x124\n" +
	"\bcomments\x18\x01 \x03(\v2\x18.user.v1.CommentResponseR\bcomments\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"V\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x02 \x01(\tR\vfollowingId\"X\n" +
	"\x12UnsubscribeRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x02 \x01(\tR\vfollowingId\"G\n" +
	"\x11SubscribeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Z\n" +
	"\x0eGetFeedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"D\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9d\n" +
	"\n" +
	"\vUserService\x12?\n" +
	"\n" +
	"CreateUser\x12\x1a.user.v1.CreateUserRequest\x1a\x15.user.v1.UserResponse\x12C\n" +
	"\x11GetUserByUsername\x12\x17.user.v1.GetUserRequest\x1a\x15.user.v1.UserResponse\x12?\n" +
	"\n" +
	"UpdateUser\x12\x1a.user.v1.UpdateUserRequest\x1a\x15.user.v1.UserResponse\x12A\n" +
	"\tListUsers\x12\x19.user.v1.ListUsersRequest\x1a\x19.user.v1.ListUserResponse\x12<\n" +
	"\aIsAdmin\x12\x17.user.v1.IsAdminRequest\x1a\x18.user.v1.IsAdminResponse\x12?\n" +
	"\bAddAdmin\x12\x18.user.v1.AddAdminRequest\x1a\x19.user.v1.AddAdminResponse\x12H\n" +
	"\vRemoveAdmin\x12\x1b.user.v1.RemoveAdminRequest\x1a\x1c.user.v1.RemoveAdminResponse\x12E\n" +
	"\rGetUserByTgID\x12\x1d.user.v1.GetUserByTgIDRequest\x1a\x15.user.v1.UserResponse\x12C\n" +
	"\fRegisterUser\x12\x1c.user.v1.RegisterUserRequest\x1a\x15.user.v1.UserResponse\x12?\n" +
	"\n" +
	"CreatePost\x12\x1a.user.v1.CreatePostRequest\x1a\x15.user.v1.PostResponse\x12E\n" +
	"\aGetPost\x12\x17.user.v1.GetPostRequest\x1a!.user.v1.PostWithCommentsResponse\x12D\n" +
	"\fGetUserPosts\x12\x1c.user.v1.GetUserPostsRequest\x1a\x16.user.v1.PostsResponse\x12A\n" +
	"\n" +
	"DeletePost\x12\x1a.user.v1.DeletePostRequest\x1a\x17.user.v1.DeleteResponse\x12B\n" +
	"\n" +
	"AddComment\x12\x1a.user.v1.AddCommentRequest\x1a\x18.user.v1.CommentResponse\x12E\n" +
	"\vGetComments\x12\x1b.user.v1.GetCommentsRequest\x1a\x19.user.v1.CommentsResponse\x12B\n" +
	"\tSubscribe\x12\x19.user.v1.SubscribeRequest\x1a\x1a.user.v1.SubscribeResponse\x12F\n" +
	"\vUnsubscribe\x12\x1b.user.v1.UnsubscribeRequest\x1a\x1a.user.v1.SubscribeResponse\x12:\n" +
	"\aGetFeed\x12\x17.user.v1.GetFeedRequest\x1a\x16.user.v1.PostsResponse\x12K\n" +
	"\fIsSubscribed\x12\x1c.user.v1.IsSubscribedRequest\x1a\x1d.user.v1.IsSubscribedResponseB\x18Z\x16./proto/user/v1;userv1b\x06proto3"

var (
	file_proto_user_proto_rawDescOnce sync.Once
	file_proto_user_proto_rawDescData []byte
)

func file_proto_user_proto_rawDescGZIP() []byte {
	file_proto_user_proto_rawDescOnce.Do(func() {
		file_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)))
	})
	return file_proto_user_proto_rawDescData
}

var file_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil),        // 0: user.v1.CreateUserRequest
	(*IsSubscribedRequest)(nil),      // 1: user.v1.IsSubscribedRequest
	(*IsSubscribedResponse)(nil),     // 2: user.v1.IsSubscribedResponse
	(*ListUsersRequest)(nil),         // 3: user.v1.ListUsersRequest
	(*ListUserResponse)(nil),         // 4: user.v1.ListUserResponse
	(*IsAdminRequest)(nil),           // 5: user.v1.IsAdminRequest
	(*IsAdminResponse)(nil),          // 6: user.v1.IsAdminResponse
	(*AddAdminRequest)(nil),          // 7: user.v1.AddAdminRequest
	(*AddAdminResponse)(nil),         // 8: user.v1.AddAdminResponse
	(*RemoveAdminRequest)(nil),       // 9: user.v1.RemoveAdminRequest
	(*RemoveAdminResponse)(nil),      // 10: user.v1.RemoveAdminResponse
	(*GetUserRequest)(nil),           // 11: user.v1.GetUserRequest
	(*GetUserByTgIDRequest)(nil),     // 12: user.v1.GetUserByTgIDRequest
	(*RegisterUserRequest)(nil),      // 13: user.v1.RegisterUserRequest
	(*UpdateUserRequest)(nil),        // 14: user.v1.UpdateUserRequest
	(*UserResponse)(nil),             // 15: user.v1.UserResponse
	(*CreatePostRequest)(nil),        // 16: user.v1.CreatePostRequest
	(*GetPostRequest)(nil),           // 17: user.v1.GetPostRequest
	(*GetUserPostsRequest)(nil),      // 18: user.v1.GetUserPostsRequest
	(*DeletePostRequest)(nil),        // 19: user.v1.DeletePostRequest
	(*PostResponse)(nil),             // 20: user.v1.PostResponse
	(*PostsResponse)(nil),            // 21: user.v1.PostsResponse
	(*PostWithCommentsResponse)(nil), // 22: user.v1.PostWithCommentsResponse
	(*AddCommentRequest)(nil),        // 23: user.v1.AddCommentRequest
	(*GetCommentsRequest)(nil),       // 24: user.v1.GetCommentsRequest
	(*CommentResponse)(nil),          // 25: user.v1.CommentResponse
	(*CommentsResponse)(nil),         // 26: user.v1.CommentsResponse
	(*SubscribeRequest)(nil),         // 27: user.v1.SubscribeRequest
	(*UnsubscribeRequest)(nil),       // 28: user.v1.UnsubscribeRequest
	(*SubscribeResponse)(nil),        // 29: user.v1.SubscribeResponse
	(*GetFeedRequest)(nil),           // 30: user.v1.GetFeedRequest
	(*DeleteResponse)(nil),           // 31: user.v1.DeleteResponse
}
var file_proto_user_proto_depIdxs = []int32{
	15, // 0: user.v1.ListUserResponse.user:type_name -> user.v1.UserResponse
	20, // 1: user.v1.PostsResponse.posts:type_name -> user.v1.PostResponse
	20, // 2: user.v1.PostWithCommentsResponse.post:type_name -> user.v1.PostResponse
	25, // 3: user.v1.PostWithCommentsResponse.comments:type_name -> user.v1.CommentResponse
	25, // 4: user.v1.CommentsResponse.comments:type_name -> user.v1.CommentResponse
	0,  // 5: user.v1.UserService.CreateUser:input_type -> user.v1.CreateUserRequest
	11, // 6: user.v1.UserService.GetUserByUsername:input_type -> user.v1.GetUserRequest
	14, // 7: user.v1.UserService.UpdateUser:input_type -> user.v1.UpdateUserRequest
	3,  // 8: user.v1.UserService.ListUsers:input_type -> user.v1.ListUsersRequest
	5,  // 9: user.v1.UserService.IsAdmin:input_type -> user.v1.IsAdminRequest
	7,  // 10: user.v1.UserService.AddAdmin:input_type -> user.v1.AddAdminRequest
	9,  // 11: user.v1.UserService.RemoveAdmin:input_type -> user.v1.RemoveAdminRequest
	12, // 12: user.v1.UserService.GetUserByTgID:input_type -> user.v1.GetUserByTgIDRequest
	13, // 13: user.v1.UserService.RegisterUser:input_type -> user.v1.RegisterUserRequest
	16, // 14: user.v1.UserService.CreatePost:input_type -> user.v1.CreatePostRequest
	17, // 15: user.v1.UserService.GetPost:input_type -> user.v1.GetPostRequest
	18, // 16: user.v1.UserService.GetUserPosts:input_type -> user.v1.GetUserPostsRequest
	19, // 17: user.v1.UserService.DeletePost:input_type -> user.v1.DeletePostRequest
	23, // 18: user.v1.UserService.AddComment:input_type -> user.v1.AddCommentRequest
	24, // 19: user.v1.UserService.GetComments:input_type -> user.v1.GetCommentsRequest
	27, // 20: user.v1.UserService.Subscribe:input_type -> user.v1.SubscribeRequest
	28, // 21: user.v1.UserService.Unsubscribe:input_type -> user.v1.UnsubscribeRequest
	30, // 22: user.v1.UserService.GetFeed:input_type -> user.v1.GetFeedRequest
	1,  // 23: user.v1.UserService.IsSubscribed:input_type -> user.v1.IsSubscribedRequest
	15, // 24: user.v1.UserService.CreateUser:output_type -> user.v1.UserResponse
	15, // 25: user.v1.UserService.GetUserByUsername:output_type -> user.v1.UserResponse
	15, // 26: user.v1.UserService.UpdateUser:output_type -> user.v1.UserResponse
	4,  // 27: user.v1.UserService.ListUsers:output_type -> user.v1.ListUserResponse
	6,  // 28: user.v1.UserService.IsAdmin:output_type -> user.v1.IsAdminResponse
	8,  // 29: user.v1.UserService.AddAdmin:output_type -> user.v1.AddAdminResponse
	10, // 30: user.v1.UserService.RemoveAdmin:output_type -> user.v1.RemoveAdminResponse
	15, // 31: user.v1.UserService.GetUserByTgID:output_type -> user.v1.UserResponse
	15, // 32: user.v1.UserService.RegisterUser:output_type -> user.v1.UserResponse
	20, // 33: user.v1.UserService.CreatePost:output_type -> user.v1.PostResponse
	22, // 34: user.v1.UserService.GetPost:output_type -> user.v1.PostWithCommentsResponse
	21, // 35: user.v1.UserService.GetUserPosts:output_type -> user.v1.PostsResponse
	31, // 36: user.v1.UserService.DeletePost:output_type -> user.v1.DeleteResponse
	25, // 37: user.v1.UserService.AddComment:output_type -> user.v1.CommentResponse
	26, // 38: user.v1.UserService.GetComments:output_type -> user.v1.CommentsResponse
	29, // 39: user.v1.UserService.Subscribe:output_type -> user.v1.SubscribeResponse
	29, // 40: user.v1.UserService.Unsubscribe:output_type -> user.v1.SubscribeResponse
	21, // 41: user.v1.UserService.GetFeed:output_type -> user.v1.PostsResponse
	2,  // 42: user.v1.UserService.IsSubscribed:output_type -> user.v1.IsSubscribedResponse
	24, // [24:43] is the sub-list for method output_type
	5,  // [5:24] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_user_proto_init() }
func file_proto_user_proto_init() {
	if File_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_proto_goTypes,
		DependencyIndexes: file_proto_user_proto_depIdxs,
		MessageInfos:      file_proto_user_proto_msgTypes,
	}.Build()
	File_proto_user_proto = out.File
	file_proto_user_proto_goTypes = nil
	file_proto_user_proto_depIdxs = nil
}
